### ISSUE TITLE
Rendering is Clippy

### ISSUE THREAD

**Issue by Porco-Rosso** [Baxter900/background-widget#1]
Hi, is the result supposed to be so clippy? 
The frame-rate is really low, and I doubt it is because my computer is too slow to handle it.

**Comment by Baxter900** [comment]
Hi there! My experience has been that it's not clippy, unless I have a bunch of stuff open.

It's a really weird behavior, because it doesn't take up much ram or cpu, so I think it's because ubersicht limits the amount of cpu the widgets each have access to. This is based off of a couple of things. For one, if I have multiple widgets bobbing up and down, and I open a lot of programs so it has trouble updating (which I will acknowledge, that part doesn't fit with my theory) only the main one, which would theoretically take the most processing power, is clippy. The second reason I think this is the case is that I played around with using the webkit blur effect on these images, and I found that even though it didn't really increase the cpu usage, it massively increased the clippy behavior, indicating that there's a limited amount of cpu the widget has access to, and on my computer it's pushing the limit.

I think what's happening is that ubersicht only allows each widget access to a % of a single core of a cpu. Thus is I fill that up, which on my computer the widget gets close to doing, but not quite there, then the widget overall slows down in it's updating. What I'd suggest you try is disabling one of the image layers from either rendering, or animating, within the widget and seeing if that looks better.

I hope this helps!

**Comment by Porco-Rosso** [comment]
wow, I didn't expect such a reply. 
I understand that the limitations might indeed be on the ubersicht side of things. I just made the comment to let you know on a possible issue for some users.

I don't think there is really any soultion you could implement besides perhaps using a different javascript library for the bluring (don't think this would help anyway)

Cool concept and idea though!
